AccountingSystem.Web/Controllers/CompanyController.cs
using AccountingSystem.Abstractions.BLL;
using AccountingSystem.Models.AccountDbModels;
using AccountingSystem.Models.AccountViewModels;
using AccountingSystem.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AccountingSystem.Web.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyManager _CompanyManager;

        public CompanyController(ICompanyManager CompanyManager)
        {
            _CompanyManager = CompanyManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetDistricts()
        {
            var result = await _CompanyManager.GetDistricts();

            return Json(result);
        }
        public async Task<IActionResult> GetOnlineCompanyList(int radio)
        {
            var result = await _CompanyManager.GetOnlineCompanyList(radio);

            return Json(result);
        }
        public async Task<IActionResult> GetCompanyListByKey(string startingKey)
        {
            var result = await _CompanyManager.GetCompanyListByKey(startingKey);
            return Json(result);
        }

        public async Task<IActionResult> GetOnlineCompanyInfo(int cpId)
        {
            var result = await _CompanyManager.GetOnlineCompanyInfo(cpId);

            return Json(result);
        }
        public async Task<IActionResult> GetLocalCompanyInfo(int cpId)
        {
            var result = await _CompanyManager.GetCompanyById(cpId);

            return Json(result);
        }
        public async Task<IActionResult> CheckCompany(string name)
        {
            var result = await _CompanyManager.CheckCompany(name);

            return Json(result);
        }

        public async Task<IActionResult> InsertUpdateOnlineCompany([FromBody] CompanyInsertUpdateViewModel FromData)
        {
            var result = await _CompanyManager.InsertUpdateOnlineCompany(FromData);
            await _CompanyManager.UpdateProfile(FromData);

            return Json(result);
        }
        public async Task<IActionResult> CheckOnlineCompany(int id)
        {
            var result = await _CompanyManager.CheckOnlineCompany(id);

            return Json(result);
        }
        public async Task<IActionResult> SMSAlertGetOnlineCompanyInfo(int cpId)
        {
            var result = await _CompanyManager.SMSAlertGetOnlineCompanyInfoAsync(cpId);

            return Json(result);
        }
        public async Task<IActionResult> SMSAlertGetOnlineCompany(int radio)
        {
            var result = await _CompanyManager.SMSAlertGetOnlineCompanyListAsync(radio);

            return Json(result);
        }
        public async Task<IActionResult> GetContactPersonsOrJobTitle(string type, int? cId)
        {
            var result = await _CompanyManager.GetContactPersonsOrJobTitle(type, cId);

            return Json(result);
        }
        public async Task<IActionResult> GetContactPersonByCompanyId(int companyId)
        {
            var result = await _CompanyManager.GetContactPersonsByCompanyId(companyId);

            return Json(result);
        }
        public async Task<IActionResult> GetContactPersonById(int id)
        {
            var result = await _CompanyManager.GetContactPersonByIdAsync(id);

            return Json(result);
        }
        public async Task<IActionResult> AddOrUpdatePerson([FromBody] ContactPerson aPerson)
        {
            if (aPerson.Id == 0)
            {
                await _CompanyManager.InsertOrUpdateCPAsync(aPerson, "I");
            }
            else
            {
                await _CompanyManager.InsertOrUpdateCPAsync(aPerson, "U");
            }

            var returnValue = await _CompanyManager.GetContactPersonsByCompanyId(aPerson.CId);
            returnValue = returnValue.OrderBy(x => x.Name).ToList(); // Ensure the result is ordered.

            return Json(returnValue);
        }
        public async Task<IActionResult> DeletePerson([FromBody] DeletePersonModel model)
        {
            await _CompanyManager.DeletePersonAsync(model.Id);

            var returnValue = await _CompanyManager.GetContactPersonsByCompanyId(model.CId);
            returnValue = returnValue.OrderBy(x => x.Name).ToList();

            return Json(returnValue);
        }
        public async Task<IActionResult> CheckCompanyNameWithId([FromBody] CheckCompanyNameWithIdModel model)
        {
            var resp = await _CompanyManager.GetCompanyByNameAsync(model.name, model.id) == null;
            return Json(resp);
        }
        public async Task<IActionResult> InsertOrUpdateCompany([FromBody] CompanyViewModel aCompany)
        {
            var resp = await _CompanyManager.InsertOrUpdateCompanyAsync(aCompany);
            return Json(resp);
        }
        public async Task<IActionResult> Delete(int companyId)
        {
            await _CompanyManager.DeleteCompanyAsync(companyId);

            return Json(true);
        }
        public async Task<IActionResult> GetCompanyById(int companyId)
        {
            var resp = await _CompanyManager.GetCompanyById(companyId);
            return Json(resp);
        }

        public IActionResult Company()
        {
            ClaimsPrincipal claimusers = HttpContext.User;
            if (claimusers.Identity.IsAuthenticated)
                return View();

            else
                return RedirectToAction("Index", "Home");
        }
    }
}

AccountingSystem.Web/Controllers/SaleController.cs
using AccountingSystem.Abstractions.BLL;
using AccountingSystem.Models.AccountViewModels;
using AccountingSystem.Web.HelperMethod;
using Hangfire;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Reporting.NETCore;
using System.Reflection;
using System.Security.Claims;


namespace AccountingSystem.Web.Controllers
{
    public class SaleController : Controller
    {
        private readonly ISaleManager _SaleManager;

        public SaleController(ISaleManager SaleManager)
        {
            _SaleManager = SaleManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> FixDownloadIssue()
        {
            await _SaleManager.FixDownloadIssue();

            return Json(true);
        }
        public async Task<IActionResult> GetOnlineJobList(string FromDate, string ToDate, string CName, int Verified, int LedgerID)
        {
            var data = await _SaleManager.GetOnlineJobList(FromDate, ToDate, CName, Verified, LedgerID);

            return Json(data);
        }
        public async Task<IActionResult> GetJobs(int cpId, string date, int adType, int adRegion)
        {
            var data = await _SaleManager.GetJobs(cpId, date, adType, adRegion);

            return Json(data);
        }
        public async Task<IActionResult> DeleteOnlineJob(int jpId)
        {
            await _SaleManager.DeleteOnlineJob(jpId);

            return Json(true);
        }
        public async Task<IActionResult> DownLoadOnlineJobs(string fromDate, string toDate, int PNPL)
        {
            var returnValue = 0;
            var isUploaded = _SaleManager.IsAllUploaded();
            if (!await isUploaded)
            {
                returnValue = 1;
            }
            else
            {

                returnValue = await _SaleManager.DownloadJobs(fromDate, toDate, PNPL);

            }
            return Json(returnValue);
        }

        public IActionResult OnlineJobs()
        {
            ClaimsPrincipal claimusers = HttpContext.User;
            if (claimusers.Identity.IsAuthenticated)
                return View();

            else
                return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> GetSalesPersonsByProductID(int productID)
        {
            var returnValue = await _SaleManager.GetSalesPersons(productID);
            return Json(returnValue);
        }
        [HttpPost]
        public async Task<IActionResult> Save([FromBody] SaveSalesDataViewModel Data)
        {
            var result = await _SaleManager.SaveSale(Data);
            return Json(result);
        }
        public async Task<IActionResult> CheckOnlineJobs(string tnolist, string cId)
        {
            var result = await _SaleManager.CheckOnlineJobsAsync(tnolist, cId);
            return Json(new { Online = result[0], Total = result[1] });
        }
        public async Task<IActionResult> GetSalesInfo(string InvoiceNo)
        {
            var result = await _SaleManager.GetSalesInfoAsync(InvoiceNo);

            return Json(result);
        }
        public async Task<IActionResult> DownloadSMSAlert(int serviceId, string fDate, string tDate)
        {
            var result = await _SaleManager.DownloadSMSAlertAsync(serviceId, fDate, tDate);

            return Json(result);
        }

        public async Task<IActionResult> PostSMSAlertApplyLimitSalePosting([FromBody] PostSMSAlertApplyLimitSale Data)
        {
            var result = await _SaleManager.PostSMSAlertApplyLimitSalePosting(Data);

            return Json(result);
        }
        public async Task<IActionResult> GetSMSAlertApplyLimitForOnlinePost(string OPIDs)
        {
            var result = await _SaleManager.GetSMSAlertApplyLimitForOnlinePost(OPIDs);

            return Json(result);
        }
        public async Task<IActionResult> PostSMSAlertApplyLimitToOnline(string OPIDs, int CMorJS, int Type)
        {
            var result = await _SaleManager.PostSMSAlertApplyLimitToOnline(OPIDs, CMorJS, Type);

            return Json(result);
        }
        public async Task<IActionResult> GetSMSAlertApplyLimit(GetSMSApplyLimit Data)
        {
            var result = await _SaleManager.GetSMSAlertApplyLimit(Data);

            return Json(result);
        }
        public async Task<IActionResult> CheckJobTitle(int productId)
        {
            var result = await _SaleManager.CheckJobTitle(productId);

            return Json(result);
        }
        public async Task<IActionResult> GetSales(string pageNo, string pageSize, int cId, int tno)
        {
            var result = await _SaleManager.GetSales(pageNo, pageSize, cId, tno);

            return Json(result);
        }
        public async Task<IActionResult> GetDeletedSales(string pageNo, string pageSize, int cId)
        {
            var result = await _SaleManager.GetDeletedSales(pageNo, pageSize, cId);

            return Json(result);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateProduct([FromBody] UpdateProductModel model)
        {
            var result = await _SaleManager.UpdateSaleProduct(model);

            return Json(result);
        }
        public async Task<IActionResult> DeleteSale(int tno, string deleteReason, int creditNote, DateTime deleteDate)
        {
            var result = await _SaleManager.DeleteSale(tno, deleteReason, creditNote, deleteDate);
            return Json(result);
        }
        public async Task<IActionResult> MakeJournalOfSale([FromBody] MakeJournalOfSales saleInfo)
        {
            var result = await _SaleManager.MakeJournalOfSale(saleInfo);
            return Json(result);
        }
        public async Task<IActionResult> GetNumberOfId(string tno)
        {
            var result = await _SaleManager.GetNumberOfId(tno);
            return Json(result);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateSaleInfo([FromBody] UpdateSalesInfo salesInfo)
        {
            var result = await _SaleManager.UpdateSaleInfoAsync(salesInfo);
            return Json(result);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateSalePosted([FromBody] MakeJournalOfSales saleInfo)
        {
            var result = await _SaleManager.UpdateSalePosted(saleInfo);
            return Json(result);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateSaleContactPersonAndRefNo([FromBody] UpdateSaleContactPersonAndRefNoModel model)
        {
            var result = await _SaleManager.UpdateSaleContactPersonAndRefNo(model);
            return Json(result);
        }

        public IActionResult NewSale(int? onlinejobId, int? onlineLedgerId, int? companyid)
        {
            ClaimsPrincipal claimsPrincipal = HttpContext.User;
            if (claimsPrincipal.Identity.IsAuthenticated)
            {
                ViewBag.OnlineJobId = onlinejobId;
                ViewBag.OnlineLedgerId = onlineLedgerId;
                ViewBag.OnlineCompanyId = companyid;
                return View();
            }

            else
                return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> GetSalesPersonListByKey(string startingKey)
        {
            var result = await _SaleManager.GetSalesPersonListByKey(startingKey);
            return Json(result);
        }


        public IActionResult EditSale()
        {
            ClaimsPrincipal claimusers = HttpContext.User;
            if (claimusers.Identity.IsAuthenticated)
                return View();

            else
                return RedirectToAction("Index", "Home");
        }

        #region candidate monetization auto billing system Using Hangfire
        public async Task DownloadCandidateMonetizationAsync()
        {
            var result = await _SaleManager.DownloadCandidateMonetizationAsync();
        }
        public async Task SalePostMonetizationBasicAsync(string serviceName)
        {
            var result = await _SaleManager.PostSMSAlertApplyLimitSalePostingNew(serviceName);

        }

        public async Task<IActionResult> SalePostMonetizationBasicAsync_Manual([FromBody] ManualSalePostMonetizationModel model)
        {
            var result = await _SaleManager.PostSMSAlertApplyLimitSalePostingNew_Manual(model.ServiceName, model.ReceivedDate, model.FromDate, model.ToDate);
            return Json(result);

        }

        public void DownloadCandidateMonetizationJob()
        {
            RecurringJob.AddOrUpdate(
                "DownloadCandidateMonetizationJob",
                () => DownloadCandidateMonetizationAsync().GetAwaiter().GetResult(),
                //Cron.Hourly
                "0 */2 * * *"
            );
        }

        public void SalesPostingMonetizationJobs()
        {
            RecurringJob.AddOrUpdate(
                "Candidate_Monetization_Sequential_Sale_Posting",
                () => RunMonetizationJobsSequentially().GetAwaiter().GetResult(),
                "0 */2 * * *" // Adjust the cron expression as needed
            );
        }

        public async Task RunMonetizationJobsSequentially()
        {
            var count = 0;

            count = await _SaleManager.SMSAlertApplyLimitCountForBilling("Candidate Monetization-Basic");
            if (count > 100)
            {
                await SalePostMonetizationBasicAsync("Candidate Monetization-Basic");
                await Task.Delay(TimeSpan.FromMinutes(10));
            }


            count = await _SaleManager.SMSAlertApplyLimitCountForBilling("Candidate Monetization-Standard");
            if (count > 100)
            {
                await SalePostMonetizationBasicAsync("Candidate Monetization-Standard");
                await Task.Delay(TimeSpan.FromMinutes(10));
            }

AccountingSystem.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@{
    var username = Context.Session.GetString("Name");
    var userId = Context.Session.GetInt32("UserID");
    var IsAccDept = Context.Session.GetInt32("AccountDep");
    // bool accountDep = user.AccountDep;

    
    //string part = ViewBag.AccordionId;

   
    // var parts = part.Split(',');
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AccountingSystem.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AccountingSystem.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" />

    <style>
        .navbar-nav a:hover {
            background-color: lightseagreen;
            cursor: pointer;
        }

        .dropdown-menu {
            min-width: 200px;
            width: auto;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-2">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="AccountingHome">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AccountingHome">Privacy</a>
                        </li> *@
                        @if (IsAccDept == 1)
                        {
                            <li class="nav-item dropdown">
                                <!-- Add dropdown class to the list item -->
                                <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Ledger
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Ledger" asp-action="ListOfServices">List of Service</a>

                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <!-- Add dropdown class to the list item -->
                                <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Journal
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Journal" asp-action="ViewJournal">View Journal</a>
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Journal" asp-action="MakeJournal">Make Journal</a>
                                </div>
                            </li>
                        }
                        <li class="nav-item dropdown">
                            <!-- Add dropdown class to the list item -->
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Sale
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @if (IsAccDept == 1)
                                {
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Sale" asp-action="OnlineJobs">Online Jobs</a>
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Sale" asp-action="NewSale">New Sale</a>
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Sale" asp-action="EditSale">Edit Sale</a>
                                    
                                }
                                @if (IsAccDept == 1 || IsAccDept == 0)
                                {
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Invoice" asp-action="CashCollection">Cash Collection</a>
                                }
                                
                                @if (IsAccDept == 1)
                                {
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Sale" asp-action="AutoBilling">Auto SMS Alert Apply Limit</a>
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Sale" asp-action="SalesReconciliation">Sales Reconciliation</a>
                                }
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <!-- Add dropdown class to the list item -->
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Invoice
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Invoice" asp-action="MakeInvoice">Make Invoice</a>
                                <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Invoice" asp-action="OnlineInvoice">Online Invoice</a>
                                @if (userId == 28 || userId == 47 || userId == 120 || userId == 55 || userId == 1002 || userId == 9 || userId == 125 || IsAccDept == 0)
                                {
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Invoice" asp-action="OnlinePaymentVarification">Online Payment Varification</a>
                                }
                                <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Invoice" asp-action="ListOfInvoice">List of Invoice</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Company
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Company">Company Details</a>                                
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <!-- Add dropdown class to the list item -->
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Report
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @if (IsAccDept == 1)
                                    {
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Report" asp-action="TrailBalance">Trail Balance</a>
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Report" asp-action="VatTaxCollectionReport">Vat Tax Collection</a>
                                    }
                                <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Invoice" asp-action="BouncedCheckReport">Bounced Cheque Report</a>
                                
                            </div>
                        </li>
                        @if (IsAccDept == 1)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Misc
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">                               
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Sale" asp-action="GetVatAndTax">VAT & TAX</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Payroll
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    @if (userId == 28 || userId == 47 || userId == 9)
                                    {
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="employeeInfo">Employee Info</a>
                                    }
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="ProvidentFundPayment">Provident Fund</a>
                                    @if (userId == 28 || userId == 9)
                                    {
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="ProvidentFundPaymentReport">Provident Fund Report</a>
                                    }
                                </div>
                            </li>
                        }
                         @* <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Payment
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="PaymentModule">Payment Module</a>
                            </div>
                        </li> *@
                    </ul>

                    <div class="navbar-text ml-auto me-2" style="font-size:13px">
                        @if (!string.IsNullOrEmpty(username))
                        {
                            <div class="p-1" style="border:1px solid lightgray">Welcome, @username !</div>
                        }
                        
                    </div>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark dropdown-item p-1 fw-bold" style="border:1px solid lightgray;font-size:13px" asp-area="" asp-controller="Home" asp-action="LogOut">[Log Out]</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AccountingSystem.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>